// Mech icon helper: inline <img> portraits rendered from the real models
// (public/thumbs/<id>.png, generated by tools/thumbs.mjs). Falls back to
// the roster emoji if a thumbnail is missing so nothing ever renders blank.
// Where a mech's badge lives. Shared with the menu prefetcher (predict.js
// warmMenuArt), which pulls every one of these down while the title screen
// is up so the roster grid paints in one go rather than filling in.
export function thumbUrl(id) { return `thumbs/${id}.png`; }

export function mechIcon(def, size = 22) {
  const r = Math.round(size * 0.22);
  const dip = Math.round(size * 0.22);
  return `<img class="mech-ico" src="${thumbUrl(def.id)}" alt="${def.icon}" ` +
    `style="width:${size}px;height:${size}px;border-radius:${r}px;object-fit:cover;` +
    `vertical-align:-${dip}px;margin-right:${Math.max(3, Math.round(size * 0.14))}px;` +
    `background:#0a121c;box-shadow:0 0 0 1px rgba(120,200,255,0.25)" ` +
    `onerror="this.outerHTML='${def.icon}'">`;
}
