// ============================================================================
// ambience.js — the ARENA BED: one looping recording per arena, under the
// fight (public/sfx/amb_<theme>.mp3, generated by tools/sfxgen.mjs).
//
// It is a MEDIA ELEMENT, not a WebAudio buffer, for the same reason the
// soundtrack is (core/music.js): a bed is half a megabyte of audio that plays
// once per round and is never triggered, so it should stream rather than be
// decoded and held. That also keeps it off the SFX bus, which is what the
// combat compressor is pumping — a bed ducking every time someone lands a
// punch is exactly what a bed must not do.
//
// Levels: the sound master (the 🔊 button) x the SFX volume x the `ambience`
// category, so it follows the same chain as everything else in the effects
// mixer and can be tucked away without touching combat.
//
// An arena with no bed, a missing file, a browser that refuses to play: all
// the same thing — silence, and nothing else changes.
// ============================================================================
import { CONFIG, sfxGain } from './config.js';

const FADE = 0.8;          // seconds, in and out (a bed must never snap on)
const STEP = 0.05;         // fade tick

export class Ambience {
  /**
   * @param {object} [audio] GameAudio — its SFX manifest names the FILE for
   *   each bed, so the extension is whatever tools/sfxgen.mjs wrote (mp3
   *   today, wav with --wav) and this never has to guess.
   */
  constructor(audio = null, base = 'sfx/') {
    this.audio = audio;
    this.base = base;
    this.arena = null;      // theme id whose bed is loaded
    this.master = 0.8;      // the sound master (0 while muted)
    this.playing = false;
    this.el = null;
    this._fade = null;
    if (typeof Audio !== 'undefined') {
      try {
        this.el = new Audio();
        this.el.loop = true;
        this.el.preload = 'none';
        this.el.volume = 0;
      } catch (e) { this.el = null; }
    }
  }

  /** The level this bed should sit at right now. */
  get target() { return this.master * sfxGain('ambience') * (CONFIG.sfxSamples ? 1 : 0); }

  /**
   * Play THIS arena's bed. Called as a fight is built; an arena with no
   * recording simply stops whatever was playing. Re-asking for the arena
   * already playing does nothing, so a round change on the same theme does
   * not restart the loop.
   */
  setArena(themeId) {
    if (!this.el) return;
    if (themeId === this.arena) return;
    this.arena = themeId || null;
    if (!themeId) { this.stop(); return; }
    try {
      const file = this.audio?._bank?.[`amb_${themeId}`]?.file || `amb_${themeId}.mp3`;
      this.el.src = new URL(this.base + file, document.baseURI).href;
      this.el.currentTime = 0;
      this.el.volume = 0;
      this.playing = true;
      const p = this.el.play();
      if (p?.catch) p.catch(() => {});   // autoplay policy / missing file
      this._to(this.target);
    } catch (e) { /* no bed for this arena */ }
  }

  /** Hold it where it is (pause menu, tab hidden). */
  pause() {
    if (!this.el || !this.playing) return;
    this.playing = false;
    try { this.el.pause(); } catch (e) { /* ok */ }
  }

  /** Continue a paused bed. */
  resume() {
    if (!this.el || this.playing || !this.arena) return;
    this.playing = true;
    const p = this.el.play();
    if (p?.catch) p.catch(() => {});
    this._to(this.target);
  }

  /** End it — the fight is over. */
  stop() {
    if (!this.el) return;
    this.playing = false;
    this.arena = null;
    this._clearFade();
    try { this.el.pause(); this.el.removeAttribute('src'); this.el.load(); } catch (e) { /* ok */ }
  }

  /** The 🔊 master, and any live change to the mixer. */
  setMaster(v) {
    this.master = Math.min(1, Math.max(0, +v || 0));
    this.refresh();
  }

  /** Re-read the level (after a settings change). */
  refresh() { if (this.playing) this._to(this.target); else if (this.el) this.el.volume = 0; }

  _clearFade() { if (this._fade) { clearInterval(this._fade); this._fade = null; } }

  /** Ramp the element's gain — a bed appearing at full level reads as a bug. */
  _to(want) {
    if (!this.el) return;
    this._clearFade();
    const per = STEP / FADE;
    this._fade = setInterval(() => {
      if (!this.el) return this._clearFade();
      const d = want - this.el.volume;
      if (Math.abs(d) <= per) { this.el.volume = want; this._clearFade(); return; }
      this.el.volume = Math.min(1, Math.max(0, this.el.volume + Math.sign(d) * per));
    }, STEP * 1000);
  }
}
