// Central feature flags. URL params override at load time:
//   ?textures=0  — disable the image texture pack (procedural skins only)
const params = typeof location !== 'undefined'
  ? new URLSearchParams(location.search)
  : { get: () => null };

// Robot-speed slider bounds. The step is what one ←→ press moves.
export const SPEED_MIN = 0.5;
export const SPEED_MAX = 2.0;
export const SPEED_STEP = 0.05;
export const SPEED_DEFAULT = 1.0;

// Music bus default, and the MENU THEME's share of it: the menus play at
// `musicVolume * menuMusicMix`, so 0.5 is "half as loud as a fight". Change
// the mix to move the menus alone; the settings slider moves the bus, and the
// menus follow it down.
export const MUSIC_VOL_DEFAULT = 0.22;
export const MENU_MUSIC_MIX_DEFAULT = 0.5;

// ---------------------------------------------------------------- SOUND FX
//
// THE RECORDED SET (public/sfx/, generated by tools/sfxgen.mjs from the
// prompts in docs/SOUND_PROMPTS.md) plays instead of the procedural synth in
// core/audio.js. `sfxSamples` is the switch; OFF is the synth, which is kept
// forever as the zero-download path and the A/B reference.
export const SFX_SAMPLES_DEFAULT = true;
//
// LEVELS ARE A CHAIN, not one number: the sound master (the 🔊 button's
// 0/0.8) x `sfxMaster` x the CATEGORY's own level. So the whole effects bed
// can be pulled down against the music without touching the balance inside
// it, and one noisy family — footsteps at two a second, a gatling at twelve —
// can be tucked under the sounds that carry the fight.
export const SFX_MASTER_DEFAULT = 0.9;
export const SFX_MIX_DEFAULT = {
  impact: 1.0,        // hits, blocks, swings, bodies landing — the fight itself
  movement: 0.55,     // footsteps, servos, jets: constant, so deliberately under
  weapon: 0.85,       // guns, beams, cryo
  destruction: 1.0,   // explosions, collapsing buildings, breaking props
  ui: 0.7,            // menu blips, stingers, the bell
  character: 0.9,     // per-mech signatures (howls, taunts, chest beats)
  surface: 0.5,       // what a foot lands IN — under the footstep, never over it
  loop: 0.6,          // sustained states: burning, electrocuted, jets held
  ambience: 0.35,     // the arena bed, which must never compete with combat
};

// Round length slider bounds, in SECONDS.
export const ROUND_MIN = 30;
export const ROUND_MAX = 300;
export const ROUND_STEP = 10;
export const ROUND_DEFAULT = 180;

const clampRound = (v) => (Number.isFinite(v)
  ? Math.round(Math.min(ROUND_MAX, Math.max(ROUND_MIN, v))) : ROUND_DEFAULT);

// settings-menu cycle order for ARENA DESIGN (labels in core/text.js) —
// declared before CONFIG, which reads it while initializing
export const ARENA_DESIGN_MODES = ['authored', 'wards', 'avenues', 'circuit', 'fallback'];

// Snapped to whole percent as well as clamped: stepping by 0.05 in binary
// floating point otherwise banks visible crumbs (1.45 stored as
// 1.4500000000000002), which then round-trips through localStorage forever.
const clampSpeed = (v) => (Number.isFinite(v)
  ? Math.round(Math.min(SPEED_MAX, Math.max(SPEED_MIN, v)) * 100) / 100
  : SPEED_DEFAULT);

export const CONFIG = {
  // use the generated PBR texture pack (src/textures/) for robots, grounds
  // and buildings; anything missing falls back to procedural automatically
  useTextures: params.get('textures') !== '0',
  // ~7s cinematic KO finisher when a round is won by a kill (never on a
  // timeout). ?finishers=0 disables at load time.
  enable_finishers: params.get('finishers') !== '0',
  // Infinite Ultimates: fire ults without a charged meter. Persisted from
  // the settings menu; ?debug=ultimates still forces it on for a session.
  debugUltimates: params.get('debug') === 'ultimates' || readPref('rw.infiniteUlts'),
  // Show all robots: include work-in-progress mechs (roster entries flagged
  // `hidden`) in the game's roster. OFF by default — the workbenches
  // (?showcase, ?rigedit, pose/skin tools, ?battle=...) always show every
  // mech regardless. Persisted from the settings menu; ?showall=1 forces on.
  showAllRobots: params.get('showall') === '1' || readPref('rw.showAllRobots'),
  // ARENA DESIGN: which design system lays out each match's arena
  // (src/arena/designs/). Five modes:
  //   'authored' (default) — an arena with a hand-built level in
  //              src/arena/authored.js plays it; every OTHER arena is
  //              generated by the default design system (wards)
  //   'wards' | 'avenues' | 'circuit' — EVERY arena is generated fresh each
  //              match by that design system, authored levels ignored
  //   'fallback' — every arena generated by the original scatter generator,
  //              exactly the old "PROCEDURAL ARENAS: ON" behavior
  // Persisted from the settings menu; ?design=<mode> forces one for a session
  // and the old ?procedural=1 still means 'fallback'. The old on/off pref
  // migrates: ON → 'fallback', OFF → 'authored'.
  arenaDesign: readArenaDesign(),
  // REVERSE CAMERA Y: which way the right stick (and a touch look-drag) pitches
  // the camera. OFF is the standard third-person feel — push DOWN and the
  // camera rises so you look down on your mech; ON gives the flight-sim
  // inversion. Persisted from the settings menu.
  reverseCameraY: readPref('rw.reverseCamY'),
  // A NEW ARENA EVERY ROUND. A best-of-three in one city is three fights on
  // one stage, and the arenas are half the game's content — so round 2 and
  // round 3 each open somewhere new (boot.js prepares the next one while the
  // current round is being fought, so the swap costs the round-end pause and
  // nothing else). `rw.set('arenaPerRound', false)` keeps a match in one place.
  arenaPerRound: true,
  // MENU FLOOR: dress the menu stage's floor with the Ironworks Foundry iron
  // plate instead of the flat dark disc. A LOOK CHOICE, deliberately one flag
  // wide — flip it to false here (or add ?menufloor=0) to get the plain floor
  // back. `menuFloorTex` names which texture-pack ground it borrows, so trying
  // another arena's floor is a one-word edit.
  menuFloorTextured: params.get('menufloor') !== '0',
  menuFloorTex: 'ground_foundry_ironplate',
  // NEON BUZZ: how loud the title sign's flicker is, 0..1 (0 = silent). The
  // dial to turn if the sign is too chatty under the music — edit the number
  // here, or pass ?neonbuzz=<0..1> for a quick try. Each individual flicker is
  // scaled a little around this by how deep that drop-out goes.
  //
  // TO ACTUALLY JUDGE IT, use the console rather than this file: `rw.set(
  // 'neonBuzzVolume', 0.05)` then `rw.buzz()` fires three flickers on demand.
  // A drop-out is a 66ms click that comes round every couple of seconds at a
  // random depth, so comparing two builds from memory is hopeless — which is
  // exactly how this dial got a reputation for doing nothing. (Mind the
  // spelling too: an unknown URL param is ignored, though boot now warns
  // about one. See core/knobs.js.)
  neonBuzzVolume: readParam01('neonbuzz', 0.15),

  // SPLIT-SCREEN POST FX: local multiplayer runs the same post chain as the
  // single view (distance haze blur, bloom, FXAA) — one composer per
  // viewport, each sized to its own rect. Total pixel work is about the same
  // as one full-screen chain (each view is a fraction of the screen), but the
  // per-pass overhead multiplies (four bloom chains at 4P), so this is a
  // TRI-STATE, defaulting to 'auto':
  //   'auto' — run them, and drop them for the session if the frame rate
  //            actually suffers (engine.js watches real frame time)
  //   'on'   — always, whatever it costs
  //   'off'  — never; plain scissored renders, as before
  // ?postfx=auto|on|off|single ('single' is the old spelling of 'off').
  splitPostFx: readSplitPost(),

  // ---- ULT FOUNTAINS (combat/fountains.js) ----
  // Ultimates are no longer charged by dealing/taking damage: golden powerup
  // fountains spawn around the arena and standing in one grants a charge.
  fountains: {
    interval: 10,     // seconds between spawn attempts
    perRobot: 2,      // board cap = live robots × this
    maxCharges: 2,    // charges a robot can hold
  },

  // ---- battle soundtrack (src/music/, streamed — see core/music.js) ----
  // MASTER SWITCH. Off means the songs are never fetched at all and battles
  // fall back to the procedural themes in core/audio.js — the flag to flip for
  // a build that must not stream media (offline/desktop packaging, a kiosk, a
  // metered connection). ?music=0 turns it off for one session; a build made
  // with RW_NO_MUSIC=1 ships no songs, which turns it off on its own.
  music: params.get('music') !== '0',
  // ---- sound effects (public/sfx/ — see the SOUND FX block above) ----
  // Play the RECORDED set where a sound has a file, falling through to the
  // synthesized version for anything that doesn't. Settings menu, persisted;
  // ?sfx=0 forces the synth for one session.
  sfxSamples: params.get('sfx') === '0' ? false : readPref('rw.sfxSamples', SFX_SAMPLES_DEFAULT),
  // The effects bed as a whole, under the sound master. `rw.set('sfxMaster',
  // 0.5)` from the console lands immediately — it is read at the point of use.
  sfxMaster: readNum('rw.sfxMaster', SFX_MASTER_DEFAULT),
  // …and per CATEGORY under that. Tune the balance here, not per sound.
  sfxMix: { ...SFX_MIX_DEFAULT },
  // Music bus level, independent of the SFX bus. Settings slider, persisted.
  musicVolume: readNum('rw.musicVol', MUSIC_VOL_DEFAULT),
  // …and the MENU THEME is quieter than that, by a set PERCENTAGE of it: it
  // plays under screens a player is reading and talking over, where the
  // fight's level is loud. Stated as a fraction of the music bus rather than
  // as a second level, so the settings slider stays the ONE music control and
  // the menus follow it down. `menuMusicVolume` is the level that falls out.
  menuMusicMix: readNum('rw.menuMusicMix', MENU_MUSIC_MIX_DEFAULT),
  // IDLE PREFETCH (game/predict.js): while the player is reading the title
  // screen or picking a robot, quietly pull down what the fight is about to
  // need — the song, the arena's textures, the models for RANDOM picks.
  // ?prefetch=0 disables. Implies `music` for the song part.
  prefetch: params.get('prefetch') !== '0',
  // Bake each arena prop's sub-meshes together by material once it is placed
  // and measured (src/arena/props.js mergePropMeshes) — same pixels, a
  // fraction of the draw calls. ?props=raw keeps the props as authored, which
  // is how the two are compared (/workbench/?edit=props).
  mergeProps: params.get('props') !== 'raw',

  // ROBOT SPEED: a global multiplier on how fast every fighter WALKS, RUNS
  // and FLIES, over the per-mech speeds tuned in the roster. 100% is now the
  // DEFAULT pace and that pace is TWICE what it used to be — the doubling
  // lives in fighter.js SPEED_BASE, so the slider reads a clean 100% at the
  // shipped feel and the old pace is 50%. The relative pace of the roster (a
  // nimble tempest against a lumbering colossus) is untouched at any
  // setting. Attacks, dashes and the speeds written into special moves are
  // deliberately NOT scaled: this is a locomotion dial, not a game-speed
  // dial. Settings slider, persisted; ?speed=<n> overrides for a session.
  robotSpeed: clampSpeed(params.get('speed') !== null
    ? parseFloat(params.get('speed'))
    : readNum('rw.robotSpeed', SPEED_DEFAULT, SPEED_MIN, SPEED_MAX)),
  // ROUND TIME in seconds — the countdown a round times out on (match.js).
  // Settings slider, persisted; ?round=<secs> overrides for a session.
  roundTime: clampRound(params.get('round') !== null
    ? parseFloat(params.get('round'))
    : readNum('rw.roundTime', ROUND_DEFAULT, ROUND_MIN, ROUND_MAX)),
};

export const SPLIT_POST_MODES = ['auto', 'on', 'off'];

function readArenaDesign() {
  const p = params.get('design');
  if (ARENA_DESIGN_MODES.includes(p)) return p;
  if (params.get('procedural') === '1') return 'fallback';
  try {
    const v = localStorage.getItem('rw.arenaDesign');
    if (ARENA_DESIGN_MODES.includes(v)) return v;
    // migrate the retired on/off pref: ON meant "generate everything" (now
    // 'fallback'), OFF meant "play the hand-built levels" (now 'authored')
    const old = localStorage.getItem('rw.proceduralArenas');
    if (old === '1') return 'fallback';
    if (old === '0') return 'authored';
  } catch (e) { /* ok */ }
  return 'authored';
}

export function setArenaDesign(mode) {
  CONFIG.arenaDesign = ARENA_DESIGN_MODES.includes(mode) ? mode : 'authored';
  try { localStorage.setItem('rw.arenaDesign', CONFIG.arenaDesign); } catch (e) { /* ok */ }
  return CONFIG.arenaDesign;
}

function readSplitPost() {
  const p = params.get('postfx');
  if (p === 'single' || p === 'off') return 'off';
  if (p === 'on' || p === 'auto') return p;
  try {
    const v = localStorage.getItem('rw.splitPostFx');
    if (SPLIT_POST_MODES.includes(v)) return v;
  } catch (e) { /* ok */ }
  return 'auto';
}

export function setSplitPostFx(mode) {
  CONFIG.splitPostFx = SPLIT_POST_MODES.includes(mode) ? mode : 'auto';
  try { localStorage.setItem('rw.splitPostFx', CONFIG.splitPostFx); } catch (e) { /* ok */ }
  return CONFIG.splitPostFx;
}

function readPref(key, dflt = false) {
  try {
    const v = localStorage.getItem(key);
    return v === null ? dflt : v === '1';
  } catch (e) { return dflt; }
}

// A 0..1 knob whose default lives in this file and which a URL param can
// override for a quick try (?neonbuzz=0.25). Unlike readNum() there is no
// stored preference behind it — it is a value you EDIT here.
function readParam01(key, dflt) {
  const v = parseFloat(params.get(key));
  return Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : dflt;
}

function readNum(key, dflt, lo = 0, hi = 1) {
  try {
    const v = parseFloat(localStorage.getItem(key));
    return Number.isFinite(v) ? Math.min(hi, Math.max(lo, v)) : dflt;
  } catch (e) { return dflt; }
}

export function setInfiniteUltimates(on) {
  CONFIG.debugUltimates = on;
  try { localStorage.setItem('rw.infiniteUlts', on ? '1' : '0'); } catch (e) { /* ok */ }
}

export function setMusicVolume(v) {
  CONFIG.musicVolume = Math.min(1, Math.max(0, +v || 0));
  try { localStorage.setItem('rw.musicVol', String(CONFIG.musicVolume)); } catch (e) { /* ok */ }
}

/** Recorded sound FX on/off (off = the procedural synth). Persisted. */
export function setSfxSamples(on) {
  CONFIG.sfxSamples = !!on;
  try { localStorage.setItem('rw.sfxSamples', CONFIG.sfxSamples ? '1' : '0'); } catch (e) { /* ok */ }
}

/** The effects bed as a whole, under the sound master. Persisted. */
export function setSfxMaster(v) {
  CONFIG.sfxMaster = Math.min(1, Math.max(0, +v || 0));
  try { localStorage.setItem('rw.sfxMaster', String(CONFIG.sfxMaster)); } catch (e) { /* ok */ }
}

/**
 * What a sound in `category` plays at, relative to the sound master — the
 * master button still scales everything on top of this. An unknown category
 * is 1.0, so a new sound is audible before anyone has decided where it sits.
 */
export function sfxGain(category) {
  const c = CONFIG.sfxMix[category];
  return CONFIG.sfxMaster * (c == null ? 1 : c);
}

/** The menu theme's share of the music bus, 0..1. Persisted. */
export function setMenuMusicMix(v) {
  CONFIG.menuMusicMix = Math.min(1, Math.max(0, +v || 0));
  try { localStorage.setItem('rw.menuMusicMix', String(CONFIG.menuMusicMix)); } catch (e) { /* ok */ }
}

/** What the MENU theme actually plays at: the bus, quieted by the mix. */
export function menuMusicVolume() { return CONFIG.musicVolume * CONFIG.menuMusicMix; }

export function setReverseCameraY(on) {
  CONFIG.reverseCameraY = on;
  try { localStorage.setItem('rw.reverseCamY', on ? '1' : '0'); } catch (e) { /* ok */ }
}

export function setRoundTime(v) {
  CONFIG.roundTime = clampRound(parseFloat(v));
  try { localStorage.setItem('rw.roundTime', String(CONFIG.roundTime)); } catch (e) { /* ok */ }
  return CONFIG.roundTime;
}

export function setRobotSpeed(v) {
  CONFIG.robotSpeed = clampSpeed(parseFloat(v));
  try { localStorage.setItem('rw.robotSpeed', String(CONFIG.robotSpeed)); } catch (e) { /* ok */ }
  return CONFIG.robotSpeed;
}

export function setShowAllRobots(on) {
  CONFIG.showAllRobots = on;
  try { localStorage.setItem('rw.showAllRobots', on ? '1' : '0'); } catch (e) { /* ok */ }
}

