// ============================================================================
// posters — pre-render every robot as a transparent PNG for the mech-select
// screen to flip through without building a model per keypress.
//
//     node tools/posters.mjs                 # whole roster
//     node tools/posters.mjs viper rhino     # just these
//
// Writes public/posters/<id>.png plus public/posters/posters.json, whose
// entries carry the WORLD-SPACE box each image spans. The runtime sizes its
// billboard to that box (src/ui/posters.js explains the contract), which is
// what makes the image-to-model handover land on the same pixels.
//
// Needs the dev server up: npm run dev.
// ============================================================================
import { chromium } from 'playwright-core';
import { mkdir, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';

const BASE = process.env.RW_URL || 'http://localhost:5173/';
const OUT = 'public/posters';

// the roster, read straight out of the source so this can never drift
const roster = [...readFileSync('src/mechs/roster.js', 'utf8')
  .matchAll(/^    id: '(\w+)'/gm)].map((m) => m[1]);
const want = process.argv.slice(2).length ? process.argv.slice(2) : roster;

const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium',
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--no-sandbox'],
});
await mkdir(OUT, { recursive: true });

const mechs = {};
let failed = 0;
for (const id of want) {
  const page = await browser.newPage({ viewport: { width: 640, height: 640 } });
  const errs = [];
  page.on('pageerror', (e) => errs.push(String(e).slice(0, 200)));
  await page.goto(`${BASE}?poster=${id}`, { waitUntil: 'networkidle' });
  // SwiftShader is slow and the GLB has to land first
  let meta = null;
  for (let i = 0; i < 60 && !meta; i++) {
    await page.waitForTimeout(500);
    meta = await page.evaluate(() => window.__poster || null);
  }
  if (!meta || meta.error) {
    console.log(`  ${id}: FAILED ${meta?.error || 'timed out'}${errs[0] ? ' · ' + errs[0] : ''}`);
    failed++;
    await page.close();
    continue;
  }
  const el = await page.$('#poster-canvas');
  await el.screenshot({ path: `${OUT}/${id}.png`, omitBackground: true });
  mechs[id] = { ndc: meta.ndc, w: meta.w, h: meta.h, yaw: meta.yaw };
  const n = meta.ndc;
  console.log(`  ${id}: ${meta.w}x${meta.h}px  ndc x[${n.x0.toFixed(3)},${n.x1.toFixed(3)}] y[${n.y0.toFixed(3)},${n.y1.toFixed(3)}]`);
  await page.close();
}

await writeFile(`${OUT}/posters.json`, `${JSON.stringify({
  note: 'generated by tools/posters.mjs — see src/ui/posters.js for the contract',
  px: 900,
  mechs,
}, null, 1)}\n`);
console.log(`\nwrote ${Object.keys(mechs).length} posters to ${OUT}${failed ? ` (${failed} failed)` : ''}`);
await browser.close();
process.exit(failed ? 1 : 0);
