// ============================================================================
// posters — pre-render every robot as a transparent PNG for the mech-select
// screen to flip through without building a model per keypress.
//
//     node tools/posters.mjs                 # whole roster
//     node tools/posters.mjs viper rhino     # just these
//
// Writes public/posters/<id>.png plus public/posters/posters.json, whose
// entries carry the WORLD-SPACE box each image spans. The runtime sizes its
// billboard to that box (src/ui/posters.js explains the contract), which is
// what makes the image-to-model handover land on the same pixels.
//
// Needs the dev server up: npm run dev.
// ============================================================================
import { chromium } from 'playwright-core';
import { mkdir, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { PNG } from 'pngjs';

const BASE = process.env.RW_URL || 'http://localhost:5173/';
const OUT = 'public/posters';

// the roster, read straight out of the source so this can never drift
const roster = [...readFileSync('src/mechs/roster.js', 'utf8')
  .matchAll(/^    id: '(\w+)'/gm)].map((m) => m[1]);
// ...and the model manifest, so a mech that HAS a GLB can be held to it
const manifest = JSON.parse(readFileSync('public/models/manifest.json', 'utf8'));
const want = process.argv.slice(2).length ? process.argv.slice(2) : roster;

const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium',
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--no-sandbox'],
});
await mkdir(OUT, { recursive: true });

// START FROM THE INDEX ALREADY ON DISK. A named run re-renders SOME mechs, and
// posters.json is one shared map — writing it from an empty object deleted every
// other mech's entry, and a mech with no entry has no poster at all as far as
// src/ui/posters.js is concerned (posterMeta returns null and mech select goes
// back to building a model per keypress). The .png on disk does not save it: the
// box is what sizes the billboard. So merge, and let each rendered mech
// overwrite only its own entry.
let mechs = {};
try {
  const prev = JSON.parse(readFileSync(`${OUT}/posters.json`, 'utf8'));
  if (prev?.mechs) mechs = prev.mechs;
} catch { /* no index yet — first run */ }
let failed = 0;
for (const id of want) {
  const page = await browser.newPage({ viewport: { width: 640, height: 640 } });
  const errs = [];
  page.on('pageerror', (e) => errs.push(String(e).slice(0, 200)));
  await page.goto(`${BASE}?poster=${id}`, { waitUntil: 'networkidle' });
  // SwiftShader is slow and the GLB has to land first
  let meta = null;
  for (let i = 0; i < 60 && !meta; i++) {
    await page.waitForTimeout(500);
    meta = await page.evaluate(() => window.__poster || null);
  }
  if (!meta || meta.error) {
    console.log(`  ${id}: FAILED ${meta?.error || 'timed out'}${errs[0] ? ' · ' + errs[0] : ''}`);
    failed++;
    await page.close();
    continue;
  }
  // ---- the two ways a poster can be silently, confidently wrong ----
  // 1. THE WRONG BODY. The select screen shows the GLB; a poster of the
  //    procedural stand-in looks like a deliberate art choice and nobody
  //    notices until they compare. Refuse to write one.
  if (!meta.isGLB && manifest[id]?.url) {
    console.log(`  ${id}: FAILED — rendered the PROCEDURAL body, but this mech has a GLB`);
    failed++;
    await page.close();
    continue;
  }
  // the page hands back a finished PNG (colour from the engine's post chain,
  // alpha from a plain pass) — no element screenshot, so nothing of the page
  // can composite in behind the robot
  await writeFile(`${OUT}/${id}.png`, Buffer.from(meta.png.split(',')[1], 'base64'));
  // 2. NO ALPHA. A page background composites under the canvas and the PNG
  //    comes out a solid rectangle, which reads as a card behind the robot.
  const png = PNG.sync.read(readFileSync(`${OUT}/${id}.png`));
  let clear = 0;
  for (let i = 3; i < png.data.length; i += 4) if (png.data[i] < 8) clear++;
  const clearPct = (100 * clear) / (png.data.length / 4);
  if (clearPct < 5) {
    console.log(`  ${id}: FAILED — only ${clearPct.toFixed(1)}% transparent; the poster has no alpha`);
    failed++;
    await page.close();
    continue;
  }
  mechs[id] = { box: meta.box, w: meta.w, h: meta.h, yaw: meta.yaw };
  const n = meta.box;
  console.log(`  ${id}: ${meta.w}x${meta.h}px  ${meta.isGLB ? 'GLB' : 'proc'}  ` +
    `${clearPct.toFixed(0)}% clear  world x[${n.u0.toFixed(2)},${n.u1.toFixed(2)}] y[${n.v0.toFixed(2)},${n.v1.toFixed(2)}]`);
  await page.close();
}

await writeFile(`${OUT}/posters.json`, `${JSON.stringify({
  note: 'generated by tools/posters.mjs — see src/ui/posters.js for the contract',
  px: 900,
  mechs,
}, null, 1)}\n`);
console.log(`\nwrote ${Object.keys(mechs).length} posters to ${OUT}${failed ? ` (${failed} failed)` : ''}`);
await browser.close();
process.exit(failed ? 1 : 0);
